name: tokenizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          
      - uses: actions/checkout@v3
      
      - name: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    name: Testing code
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with: 
          go-version: 1.17.x

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Run benchmarks
        run: go test -bench=.